### ISSUE TITLE
This solution seems to be not treeshakeable

### ISSUE THREAD

**Issue by luckylooke** [MikeMitterer/vue-ts-sfc-starter#1]
Hello 👋 
Thanks for sharing, BUT this looks like all components are loaded to project at once, even components which are not used in project are loaded into project and into initial bundle. I haven't tried it yet, just initial feeling from:

```js
import HelloWorldElements from '@mmit/vuetssfcstarter'
    Vue.use(HelloWorldElements)
```

Am I wrong?

Thanks

**Comment by MikeMitterer** [comment]
No - you are right but in my opinion there is no way at the moment to create a treeshakeable component library without writing a custom loader...

**Comment by luckylooke** [comment]
@MikeMitterer it is sad but you are right about it... I spent days looking for solution of ui library which I would like to use.. but I end up with give up npm package and use git submodule... in case of submodule the parent project takes it as its own part and everything works quite nicely.

But thank you anyway for sharing, I think your solution is usable for some project setups, it only does not fit main.

Happy coding! :)
